update cheat sheet tool

diff --git a/tools/cs b/tools/cs
--- a/tools/cs
+++ b/tools/cs
@@ -1,62 +1,62 @@
 #!/bin/bash
-NOTE_DIR="$XDG_CONFIG_HOME/cheat/cheatsheets/personal/"
 
-# if [ -p /dev/stdin ]; then
-#     # Input is being piped in (e.g., cat file | ./script.sh)
-#     raw_input=$(cat)
-# else
-#     # Input is an argument (e.g., ./script.sh "string")
-#     raw_input="$1"
-# fi
-#
-# # Ensure we actually have input
-# if [ -z "$raw_input" ]; then
-#     echo "Error: No input provided."
-#     exit 1
-# fi
-#
-#
-is_response_ok(){
-    raw_response="$1"
+source "$XDG_CONFIG_HOME/cheat/lib/parsing.sh"
+source "$XDG_CONFIG_HOME/cheat/lib/read_input.sh"
 
-    cleaned_input="$(echo "$raw_response" | sed 's/\x1b\[[0-9;]*m//g')"
+NOTE_DIR="$XDG_CONFIG_HOME/cheat/cheatsheets/community/"
 
-    if [[ "$cleaned_input" == *"Invalid permissions string"* ]]; then
-        return
-    elif [[ "$cleaned_input" == *"404 NOT FOUND"* ]]; then
-        return
-    fi
-    echo "response ok"
-}
+fuzzy_find="false"
 
-query="$1"
+while getopts "f" opt; do
+    case $opt in
+        f)
+            fuzzy_find="true"
+            ;;
+        \?)
+            echo "Invalid option"
+            exit 1
+            ;;
+    esac
+done
 
+shift $((OPTIND - 1))
 
-base_topic="$query"
-sub_topic=":root"
-if [[ "$1" == */* ]]; then
-    base_topic=$(dirname $query)
-    sub_topic=$(basename $query)
-elif [[ "$query" == *~* ]]; then
-    IFS='~' read -r base_topic sub_topic <<< "$query"
+tmp=$(mktemp)
+trap 'rm -f "$tmp"' EXIT
+
+if [[ "$fuzzy_find" == "true" ]]; then
+    note_path=$(fdfind . "$XDG_CONFIG_HOME/cheat/cheatsheets/" | sed -E 's#^.*(personal|community)/?(.*)$#\2#' | grep '.'|grep '/' | fzf)
+
+else
+    query=$(read_input $1)
+    eval $(get_parts $query)
+    note_path="$base_topic/$sub_topic"
 fi
-
-
-
-res=$(cheat "$query")
-if [[ ! $? == 0 ]]; then
-
+if ! cheat "$note_path" > "$tmp" 2> /dev/null; then
+    #TODO write to tmp dir?
     res=$(curl -s cht.sh/$query)
-    if [[ ! $(is_response_ok "$res") ]]; then
-        echo "not a valid cheat sheet"
-        exit 0
+    if ! curl -s "cht.sh/$query" -o "$tmp"; then
+        echo "failed to fetch data"
+        exit 1
     fi
-    # TODO - only make it doesnt exist
-    mkdir -p "$NOTE_DIR/$base_topic"  
-    file_path="$base_topic/$sub_topic"
-    printf "%s" "$res" > "$NOTE_DIR/$file_path"
-    res=$(printf "saved to dir: %s\n %s" "$file_path" "$res" )
-    echo "saved to dir: $file_path"
+
+    is_ok=$(is_response_ok "$tmp")
+    case "$is_ok" in
+        "invalid") echo "not a valid cheat sheet"; exit 0
+            ;;
+        "unknown") cat "$tmp"; exit 0
+            ;;
+    esac
+
+        # TODO - only make if it doesnt exist
+        dir="$NOTE_DIR/$base_topic"  
+        abs_file_path="$dir/$sub_topic"
+        mkdir -p "$dir"  
+        if [[ ! -f $abs_file_path ]]; then
+            cp "$tmp" "$abs_file_path"
+            echo "saved to dir: $note_path"
+        fi
 fi
 
-printf "%s" "$res" | batcat -l markdown
+batcat -l markdown --paging always --file-name "$note_path" "$tmp"
+#tmux neww bash -c "curl -s cht.sh/$query  | batcat -l markdown -p --paging never & while [ : ]; do sleep 1; done"
